stages:
  training_pipeline:
    cmd: python -m src.components.Data_Ingestion
    deps:
      - src/components/Data_Ingestion.py
      - src/components/Data_Transformation.py
      - src/components/Model_Trainer.py
      - src/components/Model_Optimization.py
    params:
      # Track existing model parameters
      - model_trainer.Ridge_Regression.alpha
      - model_trainer.Lasso_Regression.alpha
      - model_trainer.Random_Forest.n_estimators
      - model_trainer.Random_Forest.max_depth
      - model_trainer.Random_Forest.min_samples_split
      - model_trainer.Random_Forest.random_state
      
      # Track new SVR parameters
      - model_trainer.SVR.kernel
      - model_trainer.SVR.C
      
      # Track new XGBoost parameters
      - model_trainer.XGBoost.learning_rate
      - model_trainer.XGBoost.n_estimators
      - model_trainer.XGBoost.max_depth

      # Track hyperparameter tuning parameters
      - model_optimization.Ridge.alpha
      - model_optimization.Ridge.solver
    outs:
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/preprocessor.pkl
      - artifacts/model.pkl
      - artifacts/tuned_model.pkl