stages:
  training_pipeline:
    cmd: python -m src.components.Data_Ingestion
    deps:
      - src/components/Data_Ingestion.py
      - src/components/Data_Transformation.py
      - src/components/Model_Trainer.py
    params:
      # Track the specific parameters for each model
      - model_trainer.Ridge_Regression.alpha
      - model_trainer.Lasso_Regression.alpha
      - model_trainer.Random_Forest.n_estimators
      - model_trainer.Random_Forest.max_depth
      - model_trainer.Random_Forest.min_samples_split
      - model_trainer.Random_Forest.random_state
    outs:
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/preprocessor.pkl
      - artifacts/model.pkl